apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lhay
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0011-tenant/ci10t-786-0011-app/devfile-sample-lhay@sha256:8fcb94074ea3685fc286aef019b845ba71cdfe84544dfa30ba2a282508a9af8e
        name: my-nodejs
        resources: {}
status: {}
