apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lhay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lhay
    app.kubernetes.io/part-of: ci10t-786-0011-app
  name: devfile-sample-lhay
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lhay
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lhay
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0011-tenant/ci10t-786-0011-app/devfile-sample-lhay@sha256:8fcb94074ea3685fc286aef019b845ba71cdfe84544dfa30ba2a282508a9af8e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
